'use client';

import { useEffect, useMemo, useState } from 'react';

type Exercise = { name: string; equipment: string; sets: number; reps: string; muscle: string };
type Day = { dow: string; long: string; type: string; focus: string; ex: Exercise[] };
type AppData = { name: string; theme: 'light'|'dark'|'system'; habits: Record<string, boolean>; sets: Record<string, number>; sleep: number; protein: number; water: number };

const PROGRAM: Day[] = [
 {dow:'MON',long:'Monday',type:'Chest + Shoulders',focus:'Chest · Delts · Triceps',ex:[
  ['Incline Dumbbell Press','Dumbbell',3,'6–10','Chest'],['Dumbbell Shoulder Press','Dumbbell',3,'8–12','Shoulders'],['Cable Fly','Cable',3,'12–15','Chest'],['Cable Lateral Raise','Cable',4,'12–20','Shoulders'],['Triceps Rope Pushdown','Cable',3,'10–15','Triceps'],['Overhead Cable Triceps Extension','Cable',3,'10–15','Triceps'],['Incline Treadmill Walk','Treadmill',1,'15–20 min','Cardio']].map(toExercise)},
 {dow:'TUE',long:'Tuesday',type:'V-Taper + Back',focus:'Lats · Back · Rear Delts · Arms',ex:[['Pull-Ups','Bodyweight',3,'5–10','Back'],['Lat Pulldown','Cable',3,'8–12','Back'],['Chest-Supported Row','Machine',3,'8–12','Back'],['Single-Arm Cable Pulldown','Cable',2,'10–15','Lats'],['Reverse Pec Deck','Machine',3,'12–15','Shoulders'],['Dumbbell Curl','Dumbbell',3,'10–15','Biceps'],['Hammer Curl','Dumbbell',2,'10–15','Biceps'],['Incline Treadmill Walk','Treadmill',1,'15–20 min','Cardio']].map(toExercise)},
 {dow:'WED',long:'Wednesday',type:'Legs',focus:'Quads · Hamstrings · Calves',ex:[['Barbell Squat','Barbell',3,'6–10','Legs'],['Glute-Ham Raise','Bodyweight',3,'8–12','Hamstrings'],['Dumbbell Lunge','Dumbbell',3,'10–15','Legs'],['Lying Leg Curl','Machine',3,'10–15','Hamstrings'],['Standing Calf Raise','Machine',3,'10–15','Calves'],['Easy Treadmill Walk','Treadmill',1,'10–15 min','Cardio']].map(toExercise)},
 {dow:'THU',long:'Thursday',type:'V-Taper + Upper Body',focus:'Chest · Back · Delts · Abs',ex:[['Incline Machine Press','Machine',3,'8–12','Chest'],['Pull-Ups','Bodyweight',3,'5–10','Back'],['Chest-Supported Row','Machine',3,'8–12','Back'],['Machine Lateral Raise','Machine',4,'12–20','Shoulders'],['Straight-Arm Cable Pulldown','Cable',3,'10–15','Lats'],['Cable Fly','Cable',3,'12–15','Chest'],['Cable Crunch','Cable',3,'10–15','Core'],['Incline Treadmill Walk','Treadmill',1,'15–20 min','Cardio']].map(toExercise)},
 {dow:'FRI',long:'Friday',type:'Off',focus:'Recovery · Mobility · Sleep',ex:[]},
 {dow:'SAT',long:'Saturday',type:'Cardio + Core',focus:'Conditioning · Core',ex:[['Incline Treadmill Walk','Treadmill',1,'30–40 min','Cardio'],['Hanging Knee Raise','Bodyweight',3,'10–15','Core'],['Ab Wheel','Bodyweight',3,'6–12','Core']].map(toExercise)},
 {dow:'SUN',long:'Sunday',type:'Lower Body + Abs',focus:'Quads · Posterior Chain · Abs',ex:[['Leg Press','Machine',3,'8–12','Legs'],['Romanian Deadlift','Barbell',3,'8–10','Hamstrings'],['Leg Extension','Machine',3,'12–15','Quads'],['Seated Calf Raise','Machine',4,'12–20','Calves'],['Reverse Crunch','Bodyweight',3,'10–15','Core'],['Cable Crunch','Cable',3,'10–15','Core'],['Easy Treadmill Walk','Treadmill',1,'10–15 min','Cardio']].map(toExercise)}
];
function toExercise(x: (string | number)[]): Exercise { return {name:String(x[0]),equipment:String(x[1]),sets:Number(x[2]),reps:String(x[3]),muscle:String(x[4])}; }
const HABITS = ['8 Hours Sleep','Protein Target','Workout Completed','Exercise Duration','Water Intake','Daily Movement','Recovery'];
const QUOTES = ['Consistency compounds quietly.','Do the next useful thing.','Strong habits make strong days.','Train with intention, recover with respect.','Small actions. Serious momentum.','You do not need perfect. You need repeatable.'];
const KEY='pulseboard:v1'; const AUTH='pulseboard:session';
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function initial(): AppData{return {name:'Hasan',theme:'system',habits:{},sets:{},sleep:0,protein:0,water:0}}

export default function Page(){
 const [ready,setReady]=useState(false),[authed,setAuthed]=useState(false),[password,setPassword]=useState(''),[bad,setBad]=useState(false),[data,setData]=useState<AppData>(initial),[day,setDay]=useState((new Date().getDay()+6)%7),[tab,setTab]=useState('home'),[now,setNow]=useState(new Date()),[offline,setOffline]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved)setData({...initial(),...JSON.parse(saved)});setAuthed(sessionStorage.getItem(AUTH)==='ok')}catch{}setOffline(!navigator.onLine);setReady(true);const t=setInterval(()=>setNow(new Date()),1000);const online=()=>setOffline(false),off=()=>setOffline(true);addEventListener('online',online);addEventListener('offline',off);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{clearInterval(t);removeEventListener('online',online);removeEventListener('offline',off)}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}},[data,ready]);
 useEffect(()=>{document.documentElement.dataset.theme=data.theme},[data.theme]);
 const selected=PROGRAM[day], key=dateKey(now), progress=selected.ex.length?Math.round(selected.ex.filter((e,i)=>(data.sets[`${key}-${day}-${i}`]||0)>=e.sets).length/selected.ex.length*100):0;
 const quote=QUOTES[Math.floor((new Date(key).getTime()/86400000)%QUOTES.length)];
 const update=(patch:Partial<AppData>)=>setData(d=>({...d,...patch}));
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1800)};
 function unlock(e:React.FormEvent){e.preventDefault();if(password==='coco1513'){sessionStorage.setItem(AUTH,'ok');setAuthed(true)}else{setBad(true);setTimeout(()=>setBad(false),500)}}
 function toggleSet(i:number,s:number){const id=`${key}-${day}-${i}`,current=data.sets[id]||0;update({sets:{...data.sets,[id]:current===s?s-1:s}});notify('Workout saved locally')}
 function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pulseboard-backup.json';a.click();URL.revokeObjectURL(url)}
 if(!ready)return null;
 if(!authed)return <div className="drawer"><form className="modal" onSubmit={unlock}><div className="brand"><i className="brand-dot"/>PULSEBOARD</div><h2>Private training space.</h2><p className="muted">Your dashboard is local, private, and ready offline.</p><div className="field"><label htmlFor="password">Access code</label><input autoFocus id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" aria-invalid={bad}/></div>{bad&&<p style={{color:'var(--accent)'}}>That code did not work. Try again.</p>}<button className="button accent" style={{width:'100%',marginTop:10}}>Unlock dashboard</button><p className="mono muted" style={{marginTop:18}}>Client-side personal access gate</p></form></div>;
 return <div className="app"><div className="shell"><header className="topbar"><div className="brand"><i className="brand-dot"/>PULSEBOARD</div><div className={`online mono ${offline?'offline':''}`}><i/>{offline?'OFFLINE':'LOCAL MODE'}</div></header>
  {tab==='home'&&<><section className="hero"><div><div className="eyebrow">{selected.long.toUpperCase()} · {key}</div><h1>GOOD {now.getHours()<12?'MORNING':now.getHours()<18?'AFTERNOON':'EVENING'}, {data.name.toUpperCase()}.</h1><p>{quote} <em>Today is for {selected.type.toLowerCase()}.</em></p></div><div><div className="clock">{now.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</div><div className="date">{now.toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'})}</div></div></section><div className="grid"><section className="card"><div className="section-head"><h2>Today’s signal</h2><span className="mono muted">{progress}% complete</span></div><div className="metrics"><div className="metric"><strong>{data.sleep ? `${Math.floor(data.sleep/60)}h ${data.sleep%60}m`:'—'}</strong><span>Sleep / 8h</span></div><div className="metric"><strong>{data.protein}g</strong><span>Protein goal</span></div><div className="metric"><strong>{data.water}/8</strong><span>Water</span></div></div><div className="bar"><i style={{width:`${progress}%`}}/></div><p className="mono muted">{selected.ex.length?`${selected.ex.filter((e,i)=>(data.sets[`${key}-${day}-${i}`]||0)>=e.sets).length}/${selected.ex.length} exercises complete`:'Recovery day · protect your energy'}</p></section><section className="card"><div className="section-head"><h2>Sleep & nutrition</h2><button className="button secondary" onClick={()=>setTab('profile')}>Edit</button></div><div className="form"><div className="field"><label>Sleep minutes</label><input type="number" min="0" max="1440" value={data.sleep||''} placeholder="480" onChange={e=>update({sleep:+e.target.value})}/></div><div className="field"><label>Protein grams</label><input type="number" min="0" value={data.protein||''} placeholder="150" onChange={e=>update({protein:+e.target.value})}/></div></div></section></div></>}
  {tab==='workout'&&<><div className="hero"><div><div className="eyebrow">Weekly training journal · {key}</div><h1>{selected.type.toUpperCase()}</h1><p>{selected.focus}. Log each set and build your record.</p></div></div><div className="tabs">{PROGRAM.map((d,i)=><button key={d.dow} className={`tab ${day===i?'active':''}`} onClick={()=>setDay(i)}>{d.dow}</button>)}</div><section className="card"><div className="section-head"><h2>{selected.long} · {selected.focus}</h2><span className="mono muted">{progress}%</span></div>{selected.ex.length?<div className="workout-list">{selected.ex.map((e,i)=>{const got=data.sets[`${key}-${day}-${i}`]||0,done=got>=e.sets;return <article className={`exercise ${done?'done':''}`} key={`${e.name}-${i}`}><span className="number">{String(i+1).padStart(2,'0')}</span><div><div className="exercise-name">{e.name}</div><div className="exercise-meta">{e.muscle} · {e.equipment} · {e.sets} × {e.reps}</div></div><div className="sets">{Array.from({length:e.sets},(_,s)=><button aria-label={`Set ${s+1}`} className={`set ${s<got?'on':''}`} onClick={()=>toggleSet(i,s+1)} key={s}>{s+1}</button>)}</div></article>})}</div>:<div style={{padding:'35px 0',textAlign:'center'}}><div className="eyebrow">Recovery protocol</div><h2 style={{fontSize:40,margin:'12px 0'}}>OFF DAY</h2><p className="muted">Sleep long, hydrate, walk lightly, and return stronger tomorrow.</p></div>}</section></>}
  {tab==='habits'&&<><div className="hero"><div><div className="eyebrow">Daily systems · {key}</div><h1>HABITS.</h1><p>One authoritative checklist for the small actions that compound.</p></div></div><section className="card"><div className="section-head"><h2>Today’s habits</h2><span className="mono muted">{Object.values(data.habits).filter(Boolean).length}/{HABITS.length}</span></div><div className="habit-list">{HABITS.map(h=>{const id=`${key}-${h}`,on=!!data.habits[id];return <div className="habit" key={h}><div className="habit-row"><div><b>{h}</b><div className="small muted">{h==='Sleep Schedule'?'Aim for a consistent window':'Mark complete when the action is done'}</div></div><button className={`check ${on?'on':''}`} aria-label={`Mark ${h} complete`} onClick={()=>update({habits:{...data.habits,[id]:!on}})}>{on?'✓':''}</button></div></div>})}</div></section></>}
  {tab==='stats'&&<><div className="hero"><div><div className="eyebrow">Consistency report</div><h1>STATS.</h1><p>Your progress is calculated from local workout, habit, and recovery records.</p></div></div><section className="card"><div className="stat-grid"><div className="stat"><b>{progress}%</b><span className="mono muted">today</span></div><div className="stat"><b>{Object.values(data.habits).filter(Boolean).length}</b><span className="mono muted">habit checks</span></div><div className="stat"><b>{Object.keys(data.sets).length}</b><span className="mono muted">set events</span></div></div><div className="section-head" style={{marginTop:28}}><h2>Weekly program</h2><span className="mono muted">7-day view</span></div>{PROGRAM.map((d,i)=><div className="habit-row" style={{padding:'13px 0',borderBottom:'1px solid var(--line)'}} key={d.dow}><b>{d.dow} · {d.type}</b><span className="mono muted">{d.ex.length?`${i===day?progress:0}%`:'REST'}</span></div>)}</section></>}
  {tab==='profile'&&<><div className="hero"><div><div className="eyebrow">Personal settings</div><h1>PROFILE.</h1><p>Personalize your local dashboard. Nothing leaves this browser.</p></div></div><section className="card"><div className="form"><div className="field"><label>Your name</label><input value={data.name} onChange={e=>update({name:e.target.value})}/></div><div className="field"><label>Theme</label><select value={data.theme} onChange={e=>update({theme:e.target.value as AppData['theme']})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></div><div className="field"><label>Water glasses · target 8</label><input type="number" min="0" max="20" value={data.water} onChange={e=>update({water:+e.target.value})}/></div><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:8}}><button className="button" onClick={exportData}>Export JSON</button><button className="button secondary" onClick={()=>{if(confirm('Reset all local Pulseboard data?')){localStorage.removeItem(KEY);setData(initial());notify('Data reset')}}}>Reset data</button></div><p className="mono muted">Session access resets when this browser session ends. Personal records persist locally.</p></div></section></>}
 </div><nav className="nav" aria-label="Primary navigation">{[['home','Home'],['workout','Workout'],['habits','Habits'],['stats','Stats'],['profile','Profile']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>{toast&&<div className="toast">{toast}</div>}</div>
}
